#include "cpptest.h"

#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\calculator\src\format.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\format.c\TestSuite_createOutputStatement.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\format.c\TestSuite_formatCheck.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\format.c\TestSuite_reversePolish.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\format.c\TestSuite_strlenCheck.c"

