#include "cpptest.h"

#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\calculator\src\viewer.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\viewer.c\TestSuite_inputconsole.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\viewer.c\TestSuite_outputconsole.c"

