#include "cpptest.h"

#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\calculator\src\calc.c"
#include "C:\Program Files (x86)\Jenkins\workspace\gitSample\SampleProject\calcurator\tests\autogenerated\calculator\src\calc.c\TestSuite_calc.c"

